server:
  port: 8080
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CGonzalez97/Config-Server.git
          default-label: main
          search-paths:
          - '*service'